//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.02 at 05:03:40 BRT 
//


package com.citibank.latam.common.bind.impl;

public class RECORDTYPEImpl implements com.citibank.latam.common.bind.RECORDTYPE, com.sun.xml.bind.JAXBObject, com.citibank.latam.common.bind.impl.runtime.UnmarshallableObject, com.citibank.latam.common.bind.impl.runtime.XMLSerializable, com.citibank.latam.common.bind.impl.runtime.ValidatableObject
{

    protected java.lang.String _USERID;
    protected java.lang.String _PARENTFUNCTIONID;
    protected java.lang.String _CPFNUMBER;
    protected java.lang.String _CNPJNUMBER;
    protected java.lang.String _GROUPNAME;
    protected java.lang.String _FUNCTIONID;
    protected java.lang.String _MODULENAME;
    protected java.lang.String _MODULEID;
    protected java.lang.String _FUNCTIONNAME;
    public final static java.lang.Class version = (com.citibank.latam.common.bind.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.citibank.latam.common.bind.RECORDTYPE.class);
    }

    public java.lang.String getUSERID() {
        return _USERID;
    }

    public void setUSERID(java.lang.String value) {
        _USERID = value;
    }

    public java.lang.String getPARENTFUNCTIONID() {
        return _PARENTFUNCTIONID;
    }

    public void setPARENTFUNCTIONID(java.lang.String value) {
        _PARENTFUNCTIONID = value;
    }

    public java.lang.String getCPFNUMBER() {
        return _CPFNUMBER;
    }

    public void setCPFNUMBER(java.lang.String value) {
        _CPFNUMBER = value;
    }

    public java.lang.String getCNPJNUMBER() {
        return _CNPJNUMBER;
    }

    public void setCNPJNUMBER(java.lang.String value) {
        _CNPJNUMBER = value;
    }

    public java.lang.String getGROUPNAME() {
        return _GROUPNAME;
    }

    public void setGROUPNAME(java.lang.String value) {
        _GROUPNAME = value;
    }

    public java.lang.String getFUNCTIONID() {
        return _FUNCTIONID;
    }

    public void setFUNCTIONID(java.lang.String value) {
        _FUNCTIONID = value;
    }

    public java.lang.String getMODULENAME() {
        return _MODULENAME;
    }

    public void setMODULENAME(java.lang.String value) {
        _MODULENAME = value;
    }

    public java.lang.String getMODULEID() {
        return _MODULEID;
    }

    public void setMODULEID(java.lang.String value) {
        _MODULEID = value;
    }

    public java.lang.String getFUNCTIONNAME() {
        return _FUNCTIONNAME;
    }

    public void setFUNCTIONNAME(java.lang.String value) {
        _FUNCTIONNAME = value;
    }

    public com.citibank.latam.common.bind.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.citibank.latam.common.bind.impl.runtime.UnmarshallingContext context) {
        return new com.citibank.latam.common.bind.impl.RECORDTYPEImpl.Unmarshaller(context);
    }

    public void serializeElementBody(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_GROUPNAME!= null) {
            context.startElement("", "GROUP_NAME");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _GROUPNAME));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CNPJNUMBER!= null) {
            context.startElement("", "CNPJ_NUMBER");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CNPJNUMBER));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CPFNUMBER!= null) {
            context.startElement("", "CPF_NUMBER");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CPFNUMBER));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_USERID!= null) {
            context.startElement("", "USER_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _USERID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_MODULEID!= null) {
            context.startElement("", "MODULE_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _MODULEID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_MODULENAME!= null) {
            context.startElement("", "MODULE_NAME");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _MODULENAME));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_FUNCTIONID!= null) {
            context.startElement("", "FUNCTION_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _FUNCTIONID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_FUNCTIONNAME!= null) {
            context.startElement("", "FUNCTION_NAME");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _FUNCTIONNAME));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_PARENTFUNCTIONID!= null) {
            context.startElement("", "PARENT_FUNCTION_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _PARENTFUNCTIONID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeAttributes(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeAttributeBody(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_GROUPNAME!= null) {
            context.startElement("", "GROUP_NAME");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _GROUPNAME));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CNPJNUMBER!= null) {
            context.startElement("", "CNPJ_NUMBER");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CNPJNUMBER));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_CPFNUMBER!= null) {
            context.startElement("", "CPF_NUMBER");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _CPFNUMBER));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_USERID!= null) {
            context.startElement("", "USER_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _USERID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_MODULEID!= null) {
            context.startElement("", "MODULE_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _MODULEID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_MODULENAME!= null) {
            context.startElement("", "MODULE_NAME");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _MODULENAME));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_FUNCTIONID!= null) {
            context.startElement("", "FUNCTION_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _FUNCTIONID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_FUNCTIONNAME!= null) {
            context.startElement("", "FUNCTION_NAME");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _FUNCTIONNAME));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_PARENTFUNCTIONID!= null) {
            context.startElement("", "PARENT_FUNCTION_ID");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _PARENTFUNCTIONID));
            } catch (java.lang.Exception e) {
                com.citibank.latam.common.bind.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
    }

    public void serializeURIs(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.citibank.latam.common.bind.RECORDTYPE.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000!com.sun.msv.grammar.InterleaveExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom."
+"sun.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/g"
+"rammar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expres"
+"sion\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Lja"
+"va/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0000\u00f19}ppsq\u0000~\u0000\u0000\u0000\u00d6k\u00fbppsq\u0000~\u0000"
+"\u0000\u0000\u00bb\u009eyppsq\u0000~\u0000\u0000\u0000\u00a0\u00d0\u00f7ppsq\u0000~\u0000\u0000\u0000\u0086\u0003uppsq\u0000~\u0000\u0000\u0000k5\u00f3ppsq\u0000~\u0000\u0000\u0000Phqppsq\u0000~\u0000"
+"\u0000\u00005\u009a\u00efppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0000\u001a\u00cd"
+"mppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\t"
+"nameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.g"
+"rammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\f"
+"contentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000\u001a\u00cdbsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z"
+"\u0000\u0005valuexp\u0000p\u0000sr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt"
+"\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLco"
+"m/sun/msv/util/StringPair;xq\u0000~\u0000\u0003\u0000\u001a\u00cdWppsr\u0000#com.sun.msv.dataty"
+"pe.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv."
+"datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.dat"
+"atype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xs"
+"d.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/Stri"
+"ng;L\u0000\btypeNameq\u0000~\u0000\u001dL\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd"
+"/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000"
+"\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Pres"
+"erve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProces"
+"sor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetE"
+"xpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringP"
+"air\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001dL\u0000\fnamespaceURIq\u0000~\u0000\u001dxpq\u0000~\u0000!q\u0000"
+"~\u0000 sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tloca"
+"lNameq\u0000~\u0000\u001dL\u0000\fnamespaceURIq\u0000~\u0000\u001dxr\u0000\u001dcom.sun.msv.grammar.NameCl"
+"ass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\nGROUP_NAMEt\u0000\u0000sr\u00000com.sun.msv.grammar.Expr"
+"ession$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tsq\u0000~\u0000\u0013\u0001psq\u0000~\u0000\r\u0000"
+"\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u000bCNPJ_NUMBERq\u0000~\u0000-q\u0000~\u0000/sq\u0000"
+"~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\nCPF_NUMBERq\u0000~\u0000-q\u0000~\u0000/"
+"sq\u0000~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u0007USER_IDq\u0000~\u0000-q\u0000~\u0000/"
+"sq\u0000~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\tMODULE_IDq\u0000~\u0000-q\u0000~"
+"\u0000/sq\u0000~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u000bMODULE_NAMEq\u0000~\u0000"
+"-q\u0000~\u0000/sq\u0000~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u000bFUNCTION_ID"
+"q\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\rFUNCTIO"
+"N_NAMEq\u0000~\u0000-q\u0000~\u0000/sq\u0000~\u0000\r\u0000\u001a\u00cdmppsq\u0000~\u0000\u000f\u0000\u001a\u00cdbq\u0000~\u0000\u0014p\u0000q\u0000~\u0000\u0018sq\u0000~\u0000)t\u0000\u0012P"
+"ARENT_FUNCTION_IDq\u0000~\u0000-q\u0000~\u0000/sr\u0000\"com.sun.msv.grammar.Expressio"
+"nPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Expressio"
+"nPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Cl"
+"osedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000R[\u0000\u0005tabl"
+"et\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u0011\u0000\u0000\u00009pur\u0000![Lcom.su"
+"n.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfppppppppq\u0000~\u0000\fppppp"
+"q\u0000~\u0000\u0005ppppppppppppppppppppppq\u0000~\u0000\npppppppppppppppppppppppppppp"
+"q\u0000~\u0000\bppppppppppppppppppppppq\u0000~\u0000\u000eq\u0000~\u00001q\u0000~\u00005q\u0000~\u00009q\u0000~\u0000=q\u0000~\u0000Aq\u0000~"
+"\u0000Eq\u0000~\u0000Iq\u0000~\u0000\u0006q\u0000~\u0000Mpppppppppppppppppppq\u0000~\u0000\u000bppppppppppppppppppp"
+"pppppppppq\u0000~\u0000\tppppppppppppppppppppppppppppq\u0000~\u0000\u0007ppppppppppppp"
+"p"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.citibank.latam.common.bind.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.citibank.latam.common.bind.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------");
        }

        protected Unmarshaller(com.citibank.latam.common.bind.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.citibank.latam.common.bind.impl.RECORDTYPEImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("PARENT_FUNCTION_ID" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 15;
                            return ;
                        }
                        if (("FUNCTION_NAME" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        if (("FUNCTION_ID" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        if (("MODULE_NAME" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        if (("MODULE_ID" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 11;
                            return ;
                        }
                        if (("USER_ID" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 17;
                            return ;
                        }
                        if (("CPF_NUMBER" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 3;
                            return ;
                        }
                        if (("CNPJ_NUMBER" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 5;
                            return ;
                        }
                        if (("GROUP_NAME" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 9;
                            return ;
                        }
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  4 :
                        if (("CPF_NUMBER" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  6 :
                        if (("CNPJ_NUMBER" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("FUNCTION_ID" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("MODULE_NAME" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  0 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  12 :
                        if (("MODULE_ID" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  16 :
                        if (("PARENT_FUNCTION_ID" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  18 :
                        if (("USER_ID" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  10 :
                        if (("GROUP_NAME" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("FUNCTION_NAME" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 0;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  17 :
                            eatText0(value);
                            state = 18;
                            return ;
                        case  5 :
                            eatText1(value);
                            state = 6;
                            return ;
                        case  0 :
                            revertToParentFromText(value);
                            return ;
                        case  13 :
                            eatText2(value);
                            state = 14;
                            return ;
                        case  1 :
                            eatText3(value);
                            state = 2;
                            return ;
                        case  15 :
                            eatText4(value);
                            state = 16;
                            return ;
                        case  9 :
                            eatText5(value);
                            state = 10;
                            return ;
                        case  3 :
                            eatText6(value);
                            state = 4;
                            return ;
                        case  7 :
                            eatText7(value);
                            state = 8;
                            return ;
                        case  11 :
                            eatText8(value);
                            state = 12;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText0(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _USERID = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CNPJNUMBER = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _MODULENAME = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _FUNCTIONID = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PARENTFUNCTIONID = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _GROUPNAME = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CPFNUMBER = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _FUNCTIONNAME = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _MODULEID = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
