//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.02 at 05:03:40 BRT 
//


package com.citibank.latam.common.bind.impl;

public class XMLTYPEImpl implements com.citibank.latam.common.bind.XMLTYPE, com.sun.xml.bind.JAXBObject, com.citibank.latam.common.bind.impl.runtime.UnmarshallableObject, com.citibank.latam.common.bind.impl.runtime.XMLSerializable, com.citibank.latam.common.bind.impl.runtime.ValidatableObject
{

    protected com.citibank.latam.common.bind.RECORDLISTTYPE _RECORDLIST;
    public final static java.lang.Class version = (com.citibank.latam.common.bind.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.citibank.latam.common.bind.XMLTYPE.class);
    }

    public com.citibank.latam.common.bind.RECORDLISTTYPE getRECORDLIST() {
        return _RECORDLIST;
    }

    public void setRECORDLIST(com.citibank.latam.common.bind.RECORDLISTTYPE value) {
        _RECORDLIST = value;
    }

    public com.citibank.latam.common.bind.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.citibank.latam.common.bind.impl.runtime.UnmarshallingContext context) {
        return new com.citibank.latam.common.bind.impl.XMLTYPEImpl.Unmarshaller(context);
    }

    public void serializeElementBody(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_RECORDLIST!= null) {
            context.startElement("", "RECORD_LIST");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _RECORDLIST));
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _RECORDLIST));
            context.endAttributes();
            context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _RECORDLIST));
            context.endElement();
        }
    }

    public void serializeAttributes(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeAttributeBody(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_RECORDLIST!= null) {
            context.startElement("", "RECORD_LIST");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _RECORDLIST));
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _RECORDLIST));
            context.endAttributes();
            context.childAsElementBody(((com.sun.xml.bind.JAXBObject) _RECORDLIST));
            context.endElement();
        }
    }

    public void serializeURIs(com.citibank.latam.common.bind.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.citibank.latam.common.bind.XMLTYPE.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/l"
+"ang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0001\u00cfJdppsr\u0000\'com.sun.msv.gramm"
+"ar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv"
+"/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0001"
+"\u00cfJYsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0006\u0001\u00cfJNpp"
+"\u0000sq\u0000~\u0000\u0000\u0001\u00cfJCppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003"
+"\u0001\u00cfJ8q\u0000~\u0000\u000bpsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003"
+"expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0007xq\u0000~\u0000\u0003\u0001\u00cfJ5q\u0000~\u0000\u000bpsr\u00002com.sun.msv.gra"
+"mmar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~"
+"\u0000\n\u0001psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.s"
+"un.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar"
+".Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u0015psr\u0000#"
+"com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000"
+"\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000\u001cxq\u0000~\u0000\u0017t\u0000-com.citibank"
+".latam.common.bind.RECORDLISTTYPEt\u0000+http://java.sun.com/jaxb"
+"/xjc/dummy-elementssq\u0000~\u0000\u001bt\u0000\u000bRECORD_LISTt\u0000\u0000q\u0000~\u0000\u001asr\u0000\"com.sun.m"
+"sv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/m"
+"sv/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.gramm"
+"ar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL"
+"\u0000\u0006parentq\u0000~\u0000$[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000"
+"\u0000\u0000\u0003\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000"
+"\u0000\u00bfppppppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\u0010ppppppppp"
+"pq\u0000~\u0000\rppppppppppppppppppppppppppppppppq\u0000~\u0000\u0005ppppppppppppppppp"
+"pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp"
+"ppppppppppppppppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.citibank.latam.common.bind.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.citibank.latam.common.bind.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(com.citibank.latam.common.bind.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.citibank.latam.common.bind.impl.XMLTYPEImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("RECORD_LIST" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  1 :
                        if (("RECORD_COUNT" == ___local)&&("" == ___uri)) {
                            _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromEnterElement((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("COLUMN_COUNT" == ___local)&&("" == ___uri)) {
                            _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromEnterElement((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("COLUMN_NAME" == ___local)&&("" == ___uri)) {
                            _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromEnterElement((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("RECORD" == ___local)&&("" == ___uri)) {
                            _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromEnterElement((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromEnterElement((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname, __atts));
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  1 :
                        _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromLeaveElement((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname));
                        return ;
                    case  2 :
                        if (("RECORD_LIST" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  1 :
                        _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromEnterAttribute((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        state = 3;
                        continue outer;
                    case  1 :
                        _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromLeaveAttribute((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, ___uri, ___local, ___qname));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  0 :
                            state = 3;
                            continue outer;
                        case  1 :
                            _RECORDLIST = ((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl) spawnChildFromText((com.citibank.latam.common.bind.impl.RECORDLISTTYPEImpl.class), 2, value));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
