package com.citibank.ods.persistence.pl.dao.rdb.oracle;

import com.citibank.ods.common.persistence.dao.rdb.oracle.BaseOracleDAO;

public class BaseOracleTplDataSubscptDAO extends BaseOracleDAO {

	
	public String C_TABLE_COLUMNS = "ENROLLMENT_NBR,PROD_IMP_TYPE_CODE, FUND_NAME_TEXT,ACCT_NBR,FILE_IMPORT_CODE, SUBSCPT_OPEN_DATE, SUBJECT_TEXT, EVENT_TEXT, SUBJECT_SOL_DATE,SUBJECT_PHASE_TEXT, PHASE_RSLTN_DATE, COMMENT_TEXT, CNFRM_INCPAT_IND, RESERVE_IND, TRAINING_TERM_IND, DOCUMENT_CHECK_IND, STOCK_TRF_ORDER_IND, BKR_CODE_TEXT, PROD_KNWLG_TEXT, PLYR_CPF_NBR, PROD_RISK_LVL_QTY, INCPAT_APPRV_NAME_TEXT, PROD_NAME_TEXT, TRANSACTION_TYPE_TEXT, ADD_DIFF_AMT,INVESTMENT_AMT, LAST_APPRV_DATE, LAST_APPRV_USER_ID, LAST_UPD_DATE, LAST_UPD_USER_ID";
}
