//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.02 at 05:03:40 BRT 
//


package com.citibank.latam.common.bind;


/**
 * Java content class for RECORD_TYPE complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="RECORD_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="GROUP_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CNPJ_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPF_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MODULE_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MODULE_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FUNCTION_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FUNCTION_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PARENT_FUNCTION_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RECORDTYPE {


    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getUSERID();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setUSERID(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getPARENTFUNCTIONID();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setPARENTFUNCTIONID(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getCPFNUMBER();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setCPFNUMBER(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getCNPJNUMBER();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setCNPJNUMBER(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getGROUPNAME();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setGROUPNAME(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getFUNCTIONID();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setFUNCTIONID(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getMODULENAME();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setMODULENAME(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getMODULEID();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setMODULEID(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getFUNCTIONNAME();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setFUNCTIONNAME(java.lang.String value);

}
