//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.02 at 05:03:40 BRT 
//


package com.citibank.latam.common.bind;


/**
 * Java content class for RECORD_LIST_TYPE complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="RECORD_LIST_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RECORD_COUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COLUMN_COUNT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COLUMN_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RECORD" type="{}RECORD_TYPE" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface RECORDLISTTYPE {


    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getCOLUMNCOUNT();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setCOLUMNCOUNT(java.lang.String value);

    /**
     * Gets the value of the RECORD property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there's any setter method for the RECORD property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRECORD().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.citibank.latam.common.bind.RECORDTYPE}
     * 
     */
    java.util.List getRECORD();

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getRECORDCOUNT();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setRECORDCOUNT(java.lang.String value);

    /**
     * 
     * @return possible object is
     * {@link java.lang.String}
     */
    java.lang.String getCOLUMNNAME();

    /**
     * 
     * @param value allowed object is
     * {@link java.lang.String}
     */
    void setCOLUMNNAME(java.lang.String value);

}
