//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.1-05/30/2003 05:06 AM(java_re)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.06.02 at 05:03:40 BRT 
//


package com.citibank.latam.common.bind;


/**
 * Java content class for XML_TYPE complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="XML_TYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RECORD_LIST" type="{}RECORD_LIST_TYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface XMLTYPE {


    /**
     * 
     * @return possible object is
     * {@link com.citibank.latam.common.bind.RECORDLISTTYPE}
     */
    com.citibank.latam.common.bind.RECORDLISTTYPE getRECORDLIST();

    /**
     * 
     * @param value allowed object is
     * {@link com.citibank.latam.common.bind.RECORDLISTTYPE}
     */
    void setRECORDLIST(com.citibank.latam.common.bind.RECORDLISTTYPE value);

}
